Blind attempt at catching deploy rollback

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -37,5 +37,10 @@ echo 'Done'
 
 ./node_modules/.bin/serverless deploy --region $AWS_REGION --stage "$STAGE" -v
 
+if [ "$?" -ne "0" ]; then
+    echo 'Serverless deploy failed'
+    exit 1
+fi
+
 echo 'Running data migrations...'
 ./node_modules/.bin/serverless invoke --region $AWS_REGION --stage "$STAGE" -f migrate
